# SPRING
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: wishlist
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true

# LOGGING
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

# EXCEPTION HANDLING
exception-handling:
  debug-message-enabled: true
